# Generated by Django 5.2.9 on 2025-12-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
