# Generated by Django 5.2.9 on 2025-12-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('in anticipation', 'In anticipation'), ('rejected', 'Rejected')], default='in anticipation', max_length=15),
        ),
    ]
