# Generated by Django 5.2.9 on 2025-12-09 13:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_response_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(choices=[('tank', 'Tank'), ('heal', 'Heal'), ('damage dealer', 'Damage dealer'), ('vendor', 'Vendor'), ('guildmaster', 'Guildmaster'), ('questgiver', 'Questgiver'), ('blacksmith', 'Blacksmith'), ('leatherworker', 'Leatherworker'), ('potion maker', 'Potion maker'), ('spell master', 'Spell master')], default='tank', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(choices=[('tank', 'Tank'), ('heal', 'Heal'), ('damage dealer', 'Damage dealer'), ('vendor', 'Vendor'), ('guildmaster', 'Guildmaster'), ('questgiver', 'Questgiver'), ('blacksmith', 'Blacksmith'), ('leatherworker', 'Leatherworker'), ('potion maker', 'Potion maker'), ('spell master', 'Spell master')], default='tank', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_en_us',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_ru',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='status_en_us',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('in anticipation', 'In anticipation'), ('rejected', 'Rejected')], default='in anticipation', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='status_ru',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('in anticipation', 'In anticipation'), ('rejected', 'Rejected')], default='in anticipation', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
