# Generated by Django 5.2.9 on 2025-12-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_category_name_en_us_category_name_ru_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender_en_us',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender_ru',
        ),
    ]
